name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - name: Build aarch 64 binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --release
      - run: mv target/aarch64-unknown-linux-musl/release/static-fs target/aarch64-unknown-linux-musl/release/static-fs-linux-musl-aarch64
      - uses: actions/upload-artifact@v2
        with:
          name: aarch64-artifact
          path: target/aarch64-unknown-linux-musl/release/static-fs-linux-musl-aarch64
